### ISSUE TITLE
[UI] Query template in bookmark

### ISSUE THREAD

**Issue by at15** [at15/goyourcassandra#12]
https://github.com/sosedoff/pgweb pgweb has bookmark for connection info, we can push this further to allow user adding query template into bookmark

````yaml
- name: FindPetById
  query: select * from pet where id = ?
  params:
    - name: id
      type: int
      required: true
````
